version: "3.7"
services:
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssW0rd#db
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin@db
      - MYSQL_PASSWORD=P@ssW0rd!
    ports:
      - "3306:3306"
  pma:
      image: phpmyadmin/phpmyadmin
      container_name: lemp_phpmyadmin
      restart: always
      ports:
        - "8000:80"
      environment:
        PMA_HOST: db
      depends_on:
        - db
      volumes:
        - /etc/localtime:/etc/localtime:ro